# CI strategy for SMTK.
#
# Builders:
#
# - Fedora 31 (ci/docker/fedora31)
#   - "simple" superbuild as dependency provider
#   - no VTK/ParaView
#   - Python 2.7
#
# Wanted test sets:
#
# - OS
#   - Windows
#   - macOS
# - Compilers
#   - Ubuntu LTS
#   - CentOS
# - Features
#   - without Python
#   - Python 3 (minimum supported and latest)
# - Documentation
# - Coverage
# - Contract testing
#   - Perform an installation (from the build stage), make it an artifact, and
#     run external projects against it.
# - GUI testing
#   - Need to figure out how it works with gitlab-runner.
#   - Is offscreen rendering suitable?

.fedora31: &fedora31
    image: "kitware/cmb:ci-smtk-fedora31-20191112"

    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        CMAKE: cmake
        CTEST: ctest
        CMAKE_CONFIGURATION: fedora31
        SCCACHE_REDIS: redis://minmus:6379

.cmake_build_unix: &cmake_build_unix
    stage: build
    tags:
        - build
        - cmb
        - docker
        - linux

    script:
        - .gitlab/ci/sccache.sh
        - export PATH=$PATH:$PWD/.gitlab
        - sccache --start-server
        - sccache --show-stats
        - "$CMAKE --version"
        - "$LAUNCHER $CTEST -VV -S .gitlab/ci/ctest_configure.cmake"
        - "$LAUNCHER $CTEST -VV -S .gitlab/ci/ctest_build.cmake"
        - sccache --show-stats

    artifacts:
        expire_in: 1d
        paths:
            # The artifacts of the build.
            - build/bin/
            - build/include/
            - build/lib/
            # Generated headers.
            # XXX(globbing): Can be simplified with support from
            # https://gitlab.com/gitlab-org/gitlab-runner/issues/4840
            - build/smtk/*.h
            - build/smtk/*/*.h
            - build/smtk/*/*/*.h
            - build/smtk/*/*/*/*.h
            - build/smtk/*/*/*/*/*.h
            - build/smtk/*/*/*/*/*/*.h

            # CTest files.
            - build/CTestCustom*.cmake
            # XXX(globbing): Can be simplified with support from
            # https://gitlab.com/gitlab-org/gitlab-runner/issues/4840
            - build/CTestTestfile.cmake
            - build/*/CTestTestfile.cmake
            - build/*/*/CTestTestfile.cmake
            - build/*/*/*/CTestTestfile.cmake
            - build/*/*/*/*/CTestTestfile.cmake
            - build/Testing/

            # CDash files.
            - build/DartConfiguration.tcl
    interruptible: true

.cmake_test_unix: &cmake_test_unix
    stage: test
    tags:
        - build
        - cmb
        - docker
        - linux

    script:
        - "$LAUNCHER $CTEST -VV -S .gitlab/ci/ctest_test.cmake"

    interruptible: true

stages:
    - build
    - test

build:fedora31:
    <<:
        - *fedora31
        - *cmake_build_unix

test:fedora31:
    <<:
        - *fedora31
        - *cmake_test_unix
    dependencies:
        - build:fedora31
    needs:
        - build:fedora31
