# CI strategy for SMTK.
#
# Builders:
#
# - Fedora 31
#   * ci/docker/fedora31
#     - no VTK/ParaView
#     - Python 2.7
#   * ci/docker/fedora31-vtk
#     - VTK only, no ParaView
#     - Python 2.7
#   * ci/docker/fedora31
#     - ParaView
#     - Python 2.7
#
# Wanted test sets:
#
# - OS
#   - Windows
#   - macOS
# - Compilers
#   - Ubuntu LTS
#   - CentOS
# - Features
#   - without Python
#   - Python 3 (minimum supported and latest)
# - Documentation
# - Contract testing
#   - Perform an installation (from the build stage), make it an artifact, and
#     run external projects against it.
# - GUI testing
#   - Need to figure out how it works with gitlab-runner.
#   - Is offscreen rendering suitable?

.only_settings: &only_settings
    - merge_requests
    - branches@cmb/smtk
    - tags@cmb/smtk

.fedora31: &fedora31
    image: "kitware/cmb:ci-smtk-fedora31-20191125"

    variables:
        GIT_SUBMODULE_STRATEGY: recursive
        CMAKE: cmake
        CTEST: ctest
        CMAKE_CONFIGURATION: fedora31_plain
        SCCACHE_REDIS: redis://minmus:6379

.fedora31_vtk: &fedora31_vtk
    extends: .fedora31
    image: "kitware/cmb:ci-smtk-fedora31-vtk-20191125"

    variables:
        CMAKE_CONFIGURATION: fedora31_vtk

.fedora31_paraview: &fedora31_paraview
    extends: .fedora31_vtk
    image: "kitware/cmb:ci-smtk-fedora31-paraview-20191204"

    variables:
        CMAKE_CONFIGURATION: fedora31_paraview

.fedora31_vtk_python2: &fedora31_vtk_python2
    extends: .fedora31
    image: "kitware/cmb:ci-smtk-fedora31-vtk-python2-20191125"

    variables:
        CMAKE_CONFIGURATION: fedora31_vtk_python2

.fedora31_memcheck: &fedora31_memcheck
    extends: .fedora31_paraview

    variables:
        CMAKE_BUILD_TYPE: RelWithDebInfo

.fedora31_asan: &fedora31_asan
    extends: .fedora31_memcheck

    variables:
        CMAKE_CONFIGURATION: fedora31_asan
        CTEST_MEMORYCHECK_TYPE: AddressSanitizer
        # Disable LeakSanitizer for now. It's catching all kinds of errors that
        # need investigated or suppressed.
        CTEST_MEMORYCHECK_SANITIZER_OPTIONS: detect_leaks=0

.fedora31_coverage: &fedora31_coverage
    extends: .fedora31_paraview

    variables:
        CMAKE_BUILD_TYPE: Debug
        CMAKE_CONFIGURATION: fedora31_coverage
        CTEST_COVERAGE: 1
        CMAKE_GENERATOR: Unix Makefiles

.cmake_build_unix: &cmake_build_unix
    stage: build
    only: *only_settings
    tags:
        - build
        - cmb
        - docker
        - linux

    script:
        - .gitlab/ci/sccache.sh
        - export PATH=$PATH:$PWD/.gitlab
        - sccache --start-server
        - sccache --show-stats
        - "$CMAKE --version"
        - "$LAUNCHER $CTEST -VV -S .gitlab/ci/ctest_configure.cmake"
        - "$LAUNCHER $CTEST -VV -S .gitlab/ci/ctest_build.cmake"
        - sccache --show-stats

    artifacts:
        expire_in: 1d
        paths:
            # The artifacts of the build.
            - build/bin/
            - build/include/
            - build/lib/
            - build/smtkConfig.cmake
            - build/smtkConfigVersion.cmake
            # Generated headers.
            # XXX(globbing): Can be simplified with support from
            # https://gitlab.com/gitlab-org/gitlab-runner/issues/4840
            - build/smtk/*.h
            - build/smtk/*/*.h
            - build/smtk/*/*/*.h
            - build/smtk/*/*/*/*.h
            - build/smtk/*/*/*/*/*.h
            - build/smtk/*/*/*/*/*/*.h

            # CTest files.
            - build/PluginTests/
            - build/smtk/extension/paraview/*/testing/python/*.py
            - build/CTestCustom*.cmake
            # XXX(globbing): Can be simplified with support from
            # https://gitlab.com/gitlab-org/gitlab-runner/issues/4840
            - build/CTestTestfile.cmake
            - build/*/CTestTestfile.cmake
            - build/*/*/CTestTestfile.cmake
            - build/*/*/*/CTestTestfile.cmake
            - build/*/*/*/*/CTestTestfile.cmake
            - build/*/*/*/*/*/CTestTestfile.cmake
            - build/*/*/*/*/*/*/CTestTestfile.cmake
            - build/Testing/

            # CTest coverage files.
            - build/CMakeFiles/TargetDirectories.txt
            # XXX(globbing): Can be simplified with support from
            # https://gitlab.com/gitlab-org/gitlab-runner/issues/4840
            - build/*/*/*/*.gcno
            - build/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*/*/*/*.gcno
            - build/smtk/*/*/*/*.cxx
            - build/smtk/*/*/*/*/*.cxx
            - build/smtk/*/*/*/*/*/*.cpp
            - build/smtk/*/*/*/*/*/*.cxx
            - build/smtk/*/*/*/*/*/*/*.cpp
            - build/smtk/*/*/*/*/*/*/*.h
            - build/smtk/extension/*/CMakeFiles/*.cxx

            # CDash files.
            - build/DartConfiguration.tcl
    interruptible: true

.cmake_test_unix: &cmake_test_unix
    stage: test
    only: *only_settings
    tags:
        - build
        - cmb
        - docker
        - linux

    script:
        - "$LAUNCHER $CTEST -VV -S .gitlab/ci/ctest_test.cmake"

    interruptible: true

.cmake_test_unix_x11: &cmake_test_unix_x11
    <<: *cmake_test_unix
    tags:
        - cmb
        - docker
        - linux
        - x11

.cmake_memcheck_unix: &cmake_memcheck_unix
    stage: test
    only: *only_settings
    tags:
        - build
        - cmb
        - docker
        - linux

    script:
        - "$LAUNCHER $CTEST -VV -S .gitlab/ci/ctest_memcheck.cmake"

    interruptible: true

.cmake_memcheck_unix_x11: &cmake_memcheck_unix_x11
    <<: *cmake_memcheck_unix
    tags:
        - cmb
        - docker
        - linux
        - x11

.cmake_memcheck_unix_x11_priv: &cmake_memcheck_unix_x11_priv
    <<: *cmake_memcheck_unix
    tags:
        - cmb
        - docker
        - linux
        - privileged
        - x11

.cmake_coverage: &cmake_coverage
    stage: analyze
    only: *only_settings
    tags:
        - build
        - cmb
        - docker
        - linux

    script:
        - "$LAUNCHER $CTEST -V -S .gitlab/ci/ctest_coverage.cmake"
    coverage: '/Percentage Coverage: \d+.\d+%/'

    interruptible: true

stages:
    - build
    - test
    - analyze

build:fedora31:
    <<:
        - *fedora31
        - *cmake_build_unix

test:fedora31:
    <<:
        - *fedora31
        - *cmake_test_unix
    dependencies:
        - build:fedora31
    needs:
        - build:fedora31

build:fedora31-vtk:
    <<:
        - *fedora31_vtk
        - *cmake_build_unix

test:fedora31-vtk:
    <<:
        - *fedora31_vtk
        - *cmake_test_unix_x11
    dependencies:
        - build:fedora31-vtk
    needs:
        - build:fedora31-vtk

build:fedora31-paraview:
    <<:
        - *fedora31_paraview
        - *cmake_build_unix

test:fedora31-paraview:
    <<:
        - *fedora31_paraview
        - *cmake_test_unix_x11
    dependencies:
        - build:fedora31-paraview
    needs:
        - build:fedora31-paraview

build:fedora31-vtk-python2:
    <<:
        - *fedora31_vtk_python2
        - *cmake_build_unix

test:fedora31-vtk-python2:
    <<:
        - *fedora31_vtk_python2
        - *cmake_test_unix_x11
    dependencies:
        - build:fedora31-vtk-python2
    needs:
        - build:fedora31-vtk-python2

build:fedora31-asan:
    <<:
        - *fedora31_asan
        - *cmake_build_unix

test:fedora31-asan:
    <<:
        - *fedora31_asan
        - *cmake_memcheck_unix_x11_priv
    dependencies:
        - build:fedora31-asan
    needs:
        - build:fedora31-asan

build:fedora31-coverage:
    <<:
        - *fedora31_coverage
        - *cmake_build_unix

test:fedora31-coverage:
    <<:
        - *fedora31_coverage
        - *cmake_test_unix_x11
    artifacts:
        expire_in: 1d
        paths:
            # Generated headers.
            # XXX(globbing): Can be simplified with support from
            # https://gitlab.com/gitlab-org/gitlab-runner/issues/4840
            - build/smtk/*.h
            - build/smtk/*/*.h
            - build/smtk/*/*/*.h
            - build/smtk/*/*/*/*.h
            - build/smtk/*/*/*/*/*.h
            - build/smtk/*/*/*/*/*/*.h

            # CTest files.
            - build/CTestCustom*.cmake
            - build/Testing/

            # CTest coverage files.
            - build/CMakeFiles/TargetDirectories.txt
            # XXX(globbing): Can be simplified with support from
            # https://gitlab.com/gitlab-org/gitlab-runner/issues/4840
            - build/*/*/*/*.gcno
            - build/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*/*/*.gcno
            - build/*/*/*/*/*/*/*/*/*.gcno
            - build/*/*/*/*.gcda
            - build/*/*/*/*/*.gcda
            - build/*/*/*/*/*/*.gcda
            - build/*/*/*/*/*/*/*.gcda
            - build/*/*/*/*/*/*/*/*.gcda
            - build/*/*/*/*/*/*/*/*/*.gcda
            - build/smtk/*/*/*/*.cxx
            - build/smtk/*/*/*/*/*.cxx
            - build/smtk/*/*/*/*/*/*.cpp
            - build/smtk/*/*/*/*/*/*.cxx
            - build/smtk/*/*/*/*/*/*/*.cpp
            - build/smtk/*/*/*/*/*/*/*.h
            - build/smtk/extension/*/CMakeFiles/*.cxx

            # CDash files.
            - build/DartConfiguration.tcl
    dependencies:
        - build:fedora31-coverage
    needs:
        - build:fedora31-coverage

analyze:fedora31-coverage:
    <<:
        - *fedora31_coverage
        - *cmake_coverage
    dependencies:
        - test:fedora31-coverage
    needs:
        - test:fedora31-coverage
