include:
    # Metadata shared my many jobs
    - local: .gitlab/rules.yml
    - local: .gitlab/artifacts.yml

    # OS builds.
    - local: .gitlab/os-linux.yml
    - local: .gitlab/os-macos.yml
    - local: .gitlab/os-windows.yml

stages:
    - build
    - test
    - analyze

################################################################################
# Job declarations
#
# Each job must pull in each of the following keys:
#
#   - a "base image"
#   - a build script
#   - tags for the jobs
#   - rules for when to run the job
#
# Additionally, jobs may also contain:
#
#   - artifacts
#   - dependency/needs jobs for required jobs
################################################################################

# Linux

## Build and test

build:fedora31:
    extends:
        - .fedora31
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31:
    extends:
        - .fedora31
        - .cmake_test_linux
        - .linux_test_tags
        - .run_automatically
    dependencies:
        - build:fedora31
    needs:
        - build:fedora31

build:fedora31-vtk:
    extends:
        - .fedora31_vtk
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31-vtk:
    extends:
        - .fedora31_vtk
        - .cmake_test_linux
        - .linux_test_tags
        - .run_automatically
    dependencies:
        - build:fedora31-vtk
    needs:
        - build:fedora31-vtk

build:fedora31-paraview:
    extends:
        - .fedora31_paraview
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31-paraview:
    extends:
        - .fedora31_paraview
        - .cmake_test_linux
        - .linux_test_tags
        - .run_automatically
    dependencies:
        - build:fedora31-paraview
    needs:
        - build:fedora31-paraview

build:fedora31-nodata:
    extends:
        - .fedora31_nodata
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31-nodata:
    extends:
        - .fedora31_nodata
        - .cmake_test_linux
        - .linux_test_tags
        - .run_automatically
    dependencies:
        - build:fedora31-nodata
    needs:
        - build:fedora31-nodata

build:fedora31-vtk-python2:
    extends:
        - .fedora31_vtk_python2
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31-vtk-python2:
    extends:
        - .fedora31_vtk_python2
        - .cmake_test_linux
        - .linux_test_tags
        - .run_automatically
    dependencies:
        - build:fedora31-vtk-python2
    needs:
        - build:fedora31-vtk-python2

## Lint builds

build:fedora31-asan:
    extends:
        - .fedora31_asan
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31-asan:
    extends:
        - .fedora31_asan
        - .cmake_memcheck_linux
        - .linux_test_priv_tags
        - .run_automatically
    dependencies:
        - build:fedora31-asan
    needs:
        - build:fedora31-asan

build:fedora31-ubsan:
    extends:
        - .fedora31_ubsan
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31-ubsan:
    extends:
        - .fedora31_ubsan
        - .cmake_memcheck_linux
        - .linux_test_priv_tags
        - .run_automatically
    dependencies:
        - build:fedora31-ubsan
    needs:
        - build:fedora31-ubsan

build:fedora31-tidy:
    extends:
        - .fedora31_tidy
        - .cmake_build_linux_tidy
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

build:fedora31-coverage:
    extends:
        - .fedora31_coverage
        - .cmake_build_linux
        - .cmake_build_artifacts
        - .linux_builder_tags
        - .run_automatically

test:fedora31-coverage:
    extends:
        - .fedora31_coverage
        - .cmake_test_linux
        - .linux_test_tags
        - .cmake_coverage_artifacts
        - .run_automatically
    dependencies:
        - build:fedora31-coverage
    needs:
        - build:fedora31-coverage

analyze:fedora31-coverage:
    extends:
        - .fedora31_coverage
        - .cmake_coverage_linux
        - .linux_builder_tags
        - .run_automatically
    dependencies:
        - test:fedora31-coverage
    needs:
        - test:fedora31-coverage

# macOS

## Build and test

build:macos-plain:
    extends:
        - .macos_plain
        - .cmake_build_macos
        - .cmake_build_artifacts
        - .macos_builder_tags
        - .run_automatically

test:macos-plain:
    extends:
        - .macos_plain
        - .cmake_test_macos
        - .macos_builder_tags
        - .run_automatically
    dependencies:
        - build:macos-plain
    needs:
        - build:macos-plain

# Windows

## Build and test

build:windows-vs2019-ninja:
    extends:
        - .windows_vs2019_ninja
        - .cmake_build_windows
        - .cmake_build_artifacts
        - .windows_builder_tags
        - .run_automatically

test:windows-vs2019-ninja:
    extends:
        - .windows_vs2019_ninja
        - .cmake_test_windows
        - .windows_builder_tags
        - .run_automatically
    dependencies:
        - build:windows-vs2019-ninja
    needs:
        - build:windows-vs2019-ninja
