vtk_module(vtkDiscreteModel
  GROUPS
   CmbCore
  DEPENDS
    vtkCommonDataModel
    vtkIOCore
    vtkFiltersCore
    vtkRenderingCore
  PRIVATE_DEPENDS
    vtkInteractionStyle
    vtkRenderingFreeTypeOpenGL
    vtkRenderingOpenGL
    vtksys
  EXCLUDE_FROM_WRAP_HIERARCHY
)
