NAME
  smtkPVServerExt
DEPENDS
  ParaView::ServerManagerRendering
  # The new ParaView module layout needs this module instead.
  #ParaView::RemotingViews
  #ParaView::RemotingApplication
  #ParaView::RemotingServerManager
  VTK::CommonCore
  VTK::CommonExecutionModel
  VTK::RenderingCore
PRIVATE_DEPENDS
  ParaView::ClientServerCoreCore
  VTK::CommonDataModel
  VTK::CommonMath
  VTK::CommonTransforms
  VTK::RenderingOpenGL2
  vtkSMTKSourceExt
