set(conda_root "$ENV{CONDA_PREFIX}")
message("conda_root ${conda_root}")
set(CMAKE_SYSTEM_NAME "${CMAKE_HOST_SYSTEM_NAME}")
#message("CMAKE_SYSTEM_NAME ${CMAKE_SYSTEM_NAME}")

set(CMAKE_SYSROOT "${conda_root}/$ENV{HOST}/sysroot")
#message("CMAKE_SYSROOT ${CMAKE_SYSROOT}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE NEVER)
