vtk_module(vtkSMTKExt
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkRenderingCore
    vtkInteractionStyle
    vtkViewsCore
    vtkViewsInfovis
    vtkIOXML
    vtkIOLegacy
  TEST_DEPENDS
    vtkTestingRendering
  EXCLUDE_FROM_WRAP_HIERARCHY
)
