//=========================================================================
//  Copyright (c) Kitware, Inc.
//  All rights reserved.
//  See LICENSE.txt for details.
//
//  This software is distributed WITHOUT ANY WARRANTY; without even
//  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
//  PURPOSE.  See the above copyright notice for more information.
//=========================================================================
#ifndef smtk_common_testing_cxx_helpers_h
#define smtk_common_testing_cxx_helpers_h

#include <array>
#include <cstdlib>
#include <filesystem>
#include <iostream>
#include <sstream>
#include <string>

#if !defined(_WIN32) && !defined(WIN32)
#include <unistd.h>
#else
#include <cstdlib>
#include <io.h>
#include <random>
#include <stdlib.h>
#include <string.h>
#endif

/**\brief A function to generate a filename for testing.
  *
  * mkstemp is cumbersome and tmpnam is deprecated.
  */
inline std::string generateFilename(const std::string& prefix, const std::string& suffix)
{
#if !defined(_WIN32) && !defined(WIN32)
  std::array<char, 7> filenameTemplate{ 'X', 'X', 'X', 'X', 'X', 'X', '\0' };
  close(mkstemp(filenameTemplate.data()));
  std::remove(filenameTemplate.data());
#else
  std::array<char, 11> filenameTemplate{ 's', 'm', 't', 'k', 'X', 'X', 'X', 'X', 'X', 'X', '\0' };
  _mktemp_s(filenameTemplate.data(), 11);
#endif
  std::ostringstream filename;
  filename << prefix << filenameTemplate.data() << suffix;
  return filename.str();
}

/// Generate a unique directory given a template string containing "XXXXXX".
///
/// If the resulting path is empty, the method failed (either due to invalid input or a lack
/// of permission to create the directory).
///
/// This function behaves exactly like mkdtemp because that is what any sane person would use.
/// Except on windows because it does not provide mkdtemp(). Surprise. So we implement our own.
inline std::filesystem::path generateDirectory(std::string path_template)
{
  std::filesystem::path result;
  auto nn = path_template.rfind("XXXXXX");
  if (nn == std::string::npos)
  {
    return result;
  }
#if !defined(_WIN32) && !defined(WIN32)
  auto* dd = mkdtemp(path_template.data());
  if (!dd)
  {
    return result;
  }
  result = std::filesystem::path(path_template);
  return result;
#else
  std::random_device rd;  // a seed source for the random number engine
  std::mt19937 gen(rd()); // mersenne_twister_engine seeded with rd()
  std::uniform_int_distribution<> distrib(0, 25);

  // Use distrib to transform the random unsigned int
  // generated by gen into an int in [0, 25]
  std::error_code ec;
  do
  {
    for (int ii = 0; ii < 6; ++ii)
    {
      path_template[nn + ii] = static_cast<char>('A' + distrib(gen));
    }
    result = path_template;
    ec.clear();
  } while (!std::filesystem::create_directories(result, ec) || ec);
  return result;
#endif // _WIN32
}

/**\brief A function for unit tests that behaves like assert.
  *
  * When \a condition is non-zero, the test passes \a condition's
  * value as its output. Otherwise it throws an exception containing
  * the optional message string \a explanation.
  *
  * While this function behaves like assert, it doesn't get optimized
  * away in release builds.
  * Use this instead of assert to avoid getting "unused variable"
  * warnings in unit tests.
  */
inline int test(int condition, const std::string& explanation = std::string())
{
  if (!condition)
  {
    if (!explanation.empty())
    {
      std::cerr << "## TEST FAILURE ##\n\n  " << explanation << "\n\n## TEST FAILURE ##\n";
    }
    throw explanation;
  }
  return condition;
}

/// A macro for running tests with more verbose output messages.
#define smtkTest(condition, msg)                                                                   \
  {                                                                                                \
    std::ostringstream explanation;                                                                \
    explanation << msg; /* NOLINT(bugprone-macro-parentheses) */                                   \
    ::test(condition, explanation.str());                                                          \
  }

#endif
