<?xml version="1.0" encoding="utf-8" ?>
<!--
Generated by hand. See David for hand.
-->
<SMTK_AttributeSystem Version="2">
  <Definitions>
    <!-- Operation -->
    <AttDef Type="forwarding operator" BaseType="operation">
      <ItemDefinitions>
        <Int Name="addToCount" NumberOfRequiredValues="1" Optional="true" IsEnabledByDefault="true">
          <DefaultValue>0</DefaultValue>
        </Int>
      </ItemDefinitions>
    </AttDef>
    <!-- Result -->
    <AttDef Type="result(forwarding operator)" BaseType="result">
      <ItemDefinitions>
        <Int Name="state" NumberOfRequiredValues="1">
        </Int>
      </ItemDefinitions>
    </AttDef>
  </Definitions>
</SMTK_AttributeSystem>
