<?xml version="1.0" encoding="utf-8" ?>
<!--
Generated by hand. See David for hand.
-->
<SMTK_AttributeSystem Version="2">
  <Definitions>
    <!-- Operator -->
    <AttDef Type="outcome test" BaseType="operator">
      <ItemDefinitions>
        <Int Name="shouldSucceed" NumberOfRequiredValues="1">
          <DefaultValue>0</DefaultValue>
        </Int>
      </ItemDefinitions>
    </AttDef>
    <!-- Result -->
    <AttDef Type="result(outcome test)" BaseType="result">
      <ItemDefinitions>
        <Int Name="able to operate">
          <DefaultValue>1</DefaultValue>
        </Int>
      </ItemDefinitions>
    </AttDef>
  </Definitions>
</SMTK_AttributeSystem>
