<?xml version="1.0" encoding="utf-8" ?>
<!--
Generated by hand. See David for hand.
-->
<SMTK_AttributeSystem Version="2">
  <Definitions>
    <!-- Operator -->
    <AttDef Type="parameter test" BaseType="operator">
      <ItemDefinitions>
        <Int Name="shouldSucceedInteger" NumberOfRequiredValues="1">
          <DefaultValue>1</DefaultValue>
        </Int>
        <Double Name="shouldSucceedFloat" NumberOfRequiredValues="3">
          <DefaultValue>0., 1., 2.</DefaultValue>
        </Double>
        <String Name="shouldSucceedString" NumberOfRequiredValues="1" Extensible="1" MaxNumberOfValues="2">
          <DefaultValue>zero</DefaultValue>
        </String>
        <ModelEntity Name="shouldSucceedUUID" NumberOfRequiredValues="1" Extensible="1">
        </ModelEntity>
      </ItemDefinitions>
    </AttDef>
    <!-- Result -->
    <AttDef Type="result(parameter test)" BaseType="result"/>
  </Definitions>
</SMTK_AttributeSystem>
