vtk_module(vtkSMTK
  DEPENDS
    vtkCommonCore
    vtkCommonDataModel
    vtkCommonExecutionModel
    vtkRenderingContext2D
    vtkRenderingContextOpenGL
    vtkRenderingCore
    vtkRenderingFreeType
    vtkInteractionStyle
    vtkViewsCore
    vtkViewsInfovis
    vtkIOXML
    vtkIOLegacy
    vtkRenderingOpenGL
    vtkRenderingMatplotlib
    vtkRenderingVolumeOpenGL
    vtkRenderingFreeTypeOpenGL
  TEST_DEPENDS
    vtkInteractionStyle
    vtkRenderingContext2D
    vtkRenderingContextOpenGL
    vtkRenderingOpenGL
    vtkRenderingMatplotlib
    vtkRenderingVolumeOpenGL
    vtkRenderingFreeTypeOpenGL
    vtkTestingRendering
  EXCLUDE_FROM_WRAP_HIERARCHY
)
