<?xml version="1.0" encoding="utf-8" ?>
<!--
Generated by jade
See john for source file
-->
<SMTK_AttributeSystem Version="2">
  <Definitions>
    <AttDef Type="Material">
      <AssociationsDef Name="Material Blocks" NumberOfRequiredValues="0" Extensible="true">
        <MembershipMask>face</MembershipMask>
      </AssociationsDef>
      <ItemDefinitions>
        <Double Name="Density">
          <RangeInfo>
            <Min Inclusive="false">0.0</Min>
          </RangeInfo>
        </Double>
        <Double Name="Viscosity">
          <RangeInfo>
            <Min Inclusive="false"></Min>
          </RangeInfo>
        </Double>
      </ItemDefinitions>
    </AttDef>
    <AttDef Type="BoundaryCondition">
      <AssociationsDef Name="BC Sets" NumberOfRequiredValues="0" Extensible="true">
        <MembershipMask>edge</MembershipMask>
      </AssociationsDef>
    </AttDef>
    <AttDef Type="Velocity" BaseType="BoundaryCondition">
      <ItemDefinitions>
        <Double Name="Velocity" NumberOfRequiredValues="2"></Double>
      </ItemDefinitions>
    </AttDef>
    <AttDef Type="Pressure" BaseType="BoundaryCondition">
      <ItemDefinitions>
        <Double Name="Pressure"></Double>
      </ItemDefinitions>
    </AttDef>
  </Definitions>
</SMTK_AttributeSystem>
