/*=========================================================================

 Program:   ParaView
 Module:    $RCSfile: pqSMTKModelReaderPanel.h,v $

 =========================================================================*/
// .NAME pqSMTKModelReaderPanel - Custom object panel for vtkSMTKModelReader
// .SECTION Description
// Custom adjustments to the automatically generated object panel for the
// vtkSMTKModelReader
#include "pqAutoGeneratedObjectPanel.h"

#include "smtk/util/UUID.h"

class pqDataRepresentation;

class pqSMTKModelReaderPanel : public pqAutoGeneratedObjectPanel
{
  typedef pqAutoGeneratedObjectPanel Superclass;
  Q_OBJECT
public:
  pqSMTKModelReaderPanel(pqProxy* pxy, QWidget* p);
  ~pqSMTKModelReaderPanel();

public slots:
  /// accept the changes made to the properties
  /// changes will be propogated down to the server manager
  /// subclasses should only change properties when accept is called to work
  /// properly with undo/redo
  //virtual void accept();

protected slots:
  void updateInformationAndDomains();
  void selectEntities(QList<smtk::util::UUID> selEntities);

private slots:
  /// Called if the user accepts pending modifications
  void onDataUpdated();

protected:
    pqDataRepresentation* getRepresentation();

private:

  class pqInternal;
  pqInternal* Internal;

};
