set(CMAKE_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}-Conda")
set(CMAKE_SYSTEM_PROCESSOR conda)

set(CMAKE_SYSROOT "${conda_root}")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
